config/routes.rb
Produtos::Application.routes.draw do
  resources :products
  root 'products#index'
  
  get 'product/' => 'product#show'
  get '/products' => 'product#index'
  get '/products/:id' => 'product#destroy'

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :produto, presence: true, :uniqueness => true
	validates :valor, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale
 
  
  def set_locale
    #config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale]= I18n.locale 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end
	def new
		@product = Product.new
	end
	def create
		@product = Product.new(product_params)
		if @product.save(product_params)
			redirect_to @product
		else
			render 'new'
		end
	end
	def show
		@product = Product.find(params[:id])
	end
	def edit
		@product = Product.find(params[:id])
	end
	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to @product
		else
			render 'edit'
		end
	end
	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to @product
	end
	private
	def product_params
		params.require(:product).permit(:produto,:valor)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Produtos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p align="center" style="padding:15px;background-color:gray">
<%= link_to_unless I18n.locale == :en, "English", locale: :en %>
|
<%= link_to_unless I18n.locale == 'pt-BR', "Portuguese", locale: :'pt-BR' %>
</p>
<%= yield %>

</body>
</html>

app/views/products/edit.html.slim
a href='#{root_path}' = t('back')
- if @product.errors.any?
	- pluralize(@product.errors.count,'erro')
	- @product.errors.full_messages.each do |msg|
		br
		= msg
=form_for :product, url: product_path, method: :patch do |f|
	= t('product')
	= f.text_field :produto
	br
	= t('price')
	= f.text_field :valor
	br
	= f.submit:Atualizar

app/views/products/index.html.slim
a href='/products/new' = t('label_newproduct')
br

table width='80%' align='center'
 tr
 	th Id
 	th =t('label_product')
 	th =t('label_price')
 	th colspan='3' =t('label_opt')

 	- @products.each do |product|
	 	tr style='margin-left:auto;margin-right:auto'
	 		td = product.id
	 		td = product.produto
	 		td = product.valor
	 		td 
	 			a href= '#{product_path(product)}' = t('label_view')
	 		td
	 			a href='#{edit_product_path(product)}' = t('label_edit')
	 		td
	 			=link_to t('label_dlt'), product_path(product),method: :delete, data: {confirm:"Tem certeza?"} 

app/views/products/new.html.slim
= form_for :product, url: products_path do |f|
 p
 = f.label :produto 
 = f.text_field :produto

 p
 = f.label :valor
 = f.text_field :valor

 p
 = f.submit:Cadastrar

app/views/products/show.html.slim
p 

label = t('product')
= @product.produto
br
label = t('price')
= number_to_currency(@product.valor)
br
a href='#{root_path}' = t('back')